name: build, format, test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: go.mod
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install
        working-directory: my-app
      - run: npm run build --if-present
        working-directory: my-app
      - name: Check code formatting
        run: |
          # The gofmt -l flag lists files that are not correctly formatted.
          # The command exits with a non-zero status if any files are listed.
          unformatted_files=$(gofmt -l -s .)
          if [ -n "$unformatted_files" ]; then
            echo "The following Go files are not formatted correctly:"
            echo "$unformatted_files"
            echo "Please run 'gofmt -w -s .' on your local machine to format your code."
            exit 1
          fi          
      - name: Run unit tests
        run: go test -v
      - name: Build prod binary
        run: go build
      - name: 'Upload Server'
        uses: actions/upload-artifact@v6
        with:
          name: wishlist
          path: wishlist
          retention-days: 5        